### ISSUE TITLE
Does not work on Omnet 5.2.1 and Inet 3.6.3

### ISSUE THREAD

**Issue by ghost** [gistnetserv-uah/RPL#1]
Hi
I am probably doing something wrong, But this rpl does not work in any Omnet I tried. Any sugestions?

**Comment by ElisaRojas** [comment]
Dear @saeshma , thanks for your message. Currently @h-hosseini is the person in charge of this code, so I'm tagging him as I'm sure he'll kindly help you :)

**Comment by ghost** [comment]
> 
> 
> Dear @saeshma , thanks for your message. Currently @h-hosseini is the person in charge of this code, so I'm tagging him as I'm sure he'll kindly help you :)

Thank you! :)

**Comment by h-hosseini** [comment]
Dear Elisa, thanks for tagging me.
Dear Saeshma, could you please explain more about your problem?

**Comment by ghost** [comment]
I downloaded your code and I also downloaded OMNeT++ 5.2.1 and INET 3.6.3, but for some reason (and obviously a lot of inexperience), i have not been able to make run the simulations. It seem there are some incompatibility between OMNeT and the Inet. I don't know exactly why? I understand that I'm not been helpfully, but any suggestions might help.

Thank you

**Comment by h-hosseini** [comment]
Can you run one of the OMNeT++ examples (e,g, dyna) and the INET examples (e.g, inet\examples\adhoc\ieee80211) to check if they correctly work?

**Comment by h-hosseini** [comment]
Then, you must introduce the inet framework to your project as a reference, so select this project in the "Project Explorer" window-> right click-> properties -> select "project references" -> select "inet" from the list.

**Comment by ghost** [comment]
Dyna works fine, but ieee80211 does not. I'm downloading and installing everything again to make sure if it's not an installation error. I'll do what you told me. Later i will let you know what happened.

Thank you

**Comment by ghost** [comment]
But i can tell you that inet was linked to the project properly,

**Comment by ghost** [comment]
Mr. @h-hosseini, I ran inet 3.6.3 \adhoc\ieee80211 and dyna, both are working fine. I also loaded your project, but stil does not work. I had to change the paths though (because of the folders RPL_IEEE802154_V1 and RPL_UnlimitedRadio_V1)

**Comment by saeshma** [comment]
Mr. @h-hosseini, I ran inet 3.6.3 \adhoc\ieee80211 and dyna, both are working fine. I also loaded your project, but stil does not work. I had to change the paths though (because of the folders RPL_IEEE802154_V1 and RPL_UnlimitedRadio_V1)

**Comment by h-hosseini** [comment]
We uploaded all the RPL projects into a folder, but to run them on OMNeT++, each project must be individually placed beside INET.
... - samples - inet
                   |
                   -RPL_IEEE802154_V1
                   |
                   -RPL_UnlimitedRadio_V1
                   |

**Comment by h-hosseini** [comment]
It seems that the space characters have been eliminated. The corrected parts are 
... / samples/ inet
... / samples/RPL_IEEE802154_V1
... / samples/RPL_UnlimitedRadio_V1 .

**Comment by haideraliawan** [comment]
Hi,
I am having the same problem. I also downloaded RPL code, OMNeT++ 5.2.1 and INET 3.6.3, but i am not able to make run the simulations. I see many errors in the RPL code and It seems that there are some incompatibilites between Inet and RPL code. I don't know exactly why? Can I get the link to download the development of the old INET 3.6.3 branch. I did not use git clone command for INET to download it, I built INET while launching OMNETPP 5.2.1.

**Comment by h-hosseini** [comment]
Dear @haideraliawan , @saeshma
I will test the simulation and create an instruction to run.

**Comment by ghost** [comment]
Ok, thank you!

**Comment by saeshma** [comment]
Hi!
Thaks for being so patient and helpful!

I was able to run avoid some errors, but just before the simulation starts, a popup say there migth be problem with the simulationManager (but may involve other folders as well).

**Comment by ghost** [comment]
Hi!
Thanks for being so patient and helpful!

I was able to run the code and avoid some errors, but just before the simulation starts, a popup says there might be problem with the simulationManager (but may involve other folders as well).

**Comment by h-hosseini** [comment]
An instruction to run the simulation on OMNeT++ 5.2.1 is available in the README file.

**Comment by ghost** [comment]
Mr. @h-hosseini, thanks for helping me.
It worked fine now. The problem was solved once I made the change on the configuration file.

Thank you very much. And i also like to thanks  @ElisaRojas.

**Comment by haideraliawan** [comment]
Hi,

Thanks for the help. I am still getting an error while installing and
building error INET which is given below:

./inet/visualizer/scene/SceneOsgEarthVisualizer.h:27:10: fatal error:
osgEarthUtil/ObjectLocator: No such file or directory
 #include <osgEarthUtil/ObjectLocator>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

Can I get INET 3.6.3 directly from the git repository?

Thanks!

**Comment by h-hosseini** [comment]
Hi,
You can access INET 3.6.3 by the following link.
https://inet.omnetpp.org/2017-12-22-INET-3.6.3-released.html
Hope to be useful!

**Comment by haideraliawan** [comment]
Thanks for the reply. I downloaded and compiles INET but getting the
following error now:

RPL_IEEE802154_V1/src/networklayer/icmpv6/ICMPv6RPL.cc:26:10: fatal error:
inet/common/INETDefs.h: No such file or directory
 #include "inet/common/INETDefs.h

**Comment by h-hosseini** [comment]
If you have installed several INET versions, you must choose the only INET 3.6.3 as the RPL reference and remove other INET references/ticks (according to Step 8.iv in the README file).

**Comment by haideraliawan** [comment]
HI,

When I build RPL projects I get this error now:

RPL_IEEE802154_V1/src/routing/rpl/RPLRouting.cc: In member function
‘virtual void rpl::RPLRouting::initialize(int)’:
RPL_IEEE802154_V1/src/routing/rpl/RPLRouting.cc:287:9: error: ‘itoa’ was
not declared in this scope
         itoa(DIORedun, K_value, 10);

**Comment by ghost** [comment]
Hello again, Mr. @h-hosseini.

I have another doubt. How did you implemented the objective function? I wasn't able to identify it in the RPL Routing.

Thaks.

**Comment by h-hosseini** [comment]
Hi, 
Welcome back 
The base article we used is available [here](https://www.mdpi.com/1424-8220/14/7/11993/htm). Figure 1illustrates how the rank is determined by applying the Objective Function in the simulation.  Briefly, we (and the mentioned article) apply minimum of the number of hops as the Objective Function. In other words, a node is chosen as the preferred parent, which has the lowest number of hops to the root node in the simulation. Then the rank is also determined based on preferred parent. 
Implementation of this concept can be seen in [this file](https://github.com/gistnetserv-uah/RPL/blob/master/OMNeTpp5_2_1_INET3_6_3/RPL_IEEE802154_V1/src/routing/rpl/RPLRouting.cc) or [this file](https://github.com/gistnetserv-uah/RPL/blob/master/OMNeTpp5_2_1_INET3_6_3/RPL_UnlimitedRadio_V1/src/routing/rpl/RPLRouting.cc) or [this file](https://github.com/gistnetserv-uah/RPL/blob/master/OMNeTpp5_2_1_INET3_6_3/RPL_UnlimitedRadio_V2/src/routing/rpl/RPLRouting.cc):

1. if (myNetwAddr==sinkAddress) : In this conditional block, You can define the rank initial value, based on your Objective Function, in the simulation.

1. Rank=Parents[VersionNember][0].ParentRank+1; At AddParent() : the rank is increased 1 hop.
you can change this value based on your Objective Function.

Hope to be useful!

**Comment by haideraliawan** [comment]
Hi,

Thanks for sharing this useful information. First of all I am not able to
open the link given in your previous email "Implementation of this concept
can be seen in this file
<https://github.com/gistnetserv-uah/RPL/blob/master/RPL_UnlimitedRadio_V1/src/routing/rpl/RPLRouting.cc>
".
Moreover, I followed all the instructions to download and install Omnetpp
5.2.1 and Inet 3.6.3. I managed to download the RPL code. But when I build
RPL  project, I get an error message in file
"rpl/src/routing/rpl/RPLRouting.cc". The error message is  "itoa (DIORedun,
K_value, 10)" was not declared in this scop". So I am not able to build and
run the project.

**Comment by h-hosseini** [comment]
Thanks for informing the corrupted link! 
The links have been edited.
In the case of the error message, if you agree, I can connect to your PC via a desktop sharing application to see what happens.

**Comment by haideraliawan** [comment]
Sure. My team viewer is on. You can connect to my PC now.
ID: *******
Password : ****

**Comment by h-hosseini** [comment]
Unfortunately, Team Viewer is not accessible here. Sorry!
Can you use [Ammy Admin](http://www.ammyy.com/en/)?

**Comment by haideraliawan** [comment]
I think it is only for windows and i am using Ubuntu. Please recommend any
alternative to Ammyy Admin for Linux.

**Comment by h-hosseini** [comment]
Unfortunately, I couldn't find any alternative.

Anyway, your installation and configuration should be like these figures. Are they alike?

![image1](https://user-images.githubusercontent.com/34283881/50843250-94cfd900-137d-11e9-88c7-e78a32221e1a.jpg)

If your OMNeT++ uses the gcc compiler, maybe it uses your linux gcc. If so, make sure your compiler version is compatible with the OMNeT++ requirements. In this case, you can also read/edit the configure.user file. _**We used the default compiler installed by OMNeT++**_. 

And also check the Project References.

![image2](https://user-images.githubusercontent.com/34283881/50843251-94cfd900-137d-11e9-9458-d6e84c288376.jpg)

**Comment by haideraliawan** [comment]
Yes. I have removed RPL_UnlimitedRadio_V1 and RPL_UnlimitedRadio_V2. I also
have changed the name of the RPL_IEEE402154_V1 to rpl. I am sending you the
figures, may be you will get an idea what is going wrong with my project.
Sorry for the bad images quality.

**Comment by h-hosseini** [comment]
I can not see the figures (there is not any figure on the post). Regarding the name of the RPL_IEEE402154_V1 or other projects, feel free to rename them.

**Comment by h-hosseini** [comment]
Dear @haideraliawan ,
I will install OMNeT++ 5.2.1 on the Ubuntu 16.04 and run the simulations to check the problem.

**Comment by haideraliawan** [comment]
Ok. I will be waiting for your response.
Thanks!

**Comment by h-hosseini** [comment]
Dear @haideraliawan ,

Compiler of OMNeT++5.2.1 is MinGW x64-(version 7.1.0), and compiler of Ubuntu 16.04 is 
```bash
(Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609.
```
MinGW x**64** supports the function of "itoa( )" in its library, but Ubuntu doesn't support it. Therefore, you can implement this function or use a same function or method.

Regarding the project name, there is no problem to rename the project name, but you must create a new folder, "rpl", in the project. Then, move "simulation" and "src" to this folder. Finally, change all inclusion file paths from "src/..." to "rpl/src/...", e.g. 
```bash
#include "src/networklayer/test1.h" 
#include "rpl/src/networklayer/test1.h"
```

Dear @ElisaRojas ,
perhaps it is better to modify the simulation based on both Windows and Linux after last revision.

**Comment by haideraliawan** [comment]
Hi,

Thanks for the help.

I am using "sprintf(K_Value,"%d", DIORedun)" instead of using
"itoa(DIORedun, K_Value, 10)". I do not get any error message but
simulation crashes in the middle. I tried to debug and got this message
"can't find a source file at
"build/glibc-OTsEL5/glibc-2.27/libio/iofclose.c".

**Comment by haideraliawan** [comment]
HI,

I have some question about INET 3.6.3. Does it require omnetpp 5.3.1 ? And
does it support RPL protocol implementation in omnetpp5.3.1??  Rpl
implementation is not available in Latest version of omnetpp or INET?

Thanks!

**Comment by ElisaRojas** [comment]
Hi @haideraliawan , did you manage to make it work?
Unfortunately, this work is done for some research we're working on... and right now we are not envisioning an update for it. If you really need it, I'd say you better use the same version just in case (OMNeT++ is constantly being updated and it's difficult to catch up otherwise).

**Comment by AREEG94FAHAD** [comment]
Hi @ElisaRojas  @h-hosseini  thank you so much for your effort, help and responses. I have a question where can I find result after run ?

**Comment by h-hosseini** [comment]
> 
> 
> Hi @ElisaRojas @h-hosseini thank you so much for your effort, help and responses. I have a question where can I find result after run ?

Hi @AREEG94FAHAD, 
First, I suggest you download and install the latest version (RPL_UnlimitedRadio_V3) because it is the most complete version.
![1](https://user-images.githubusercontent.com/34283881/116423681-279a2780-a856-11eb-8783-4b1a8e755d33.jpg)

After installation, follow the following steps to see results.

1. we put our simulated scenarios in "simulations" folder.
![2](https://user-images.githubusercontent.com/34283881/116423707-2d900880-a856-11eb-9e68-0d57b0ea1676.jpg)

2. There is a simple scenario, called test1, in the folder, and I suggest you run one of its sub folder (scenario) first.
![3](https://user-images.githubusercontent.com/34283881/116424872-1dc4f400-a857-11eb-9265-e1de53a8554b.jpg)

3. Settings for each mode of RPL (MOD 0, 1, 2) are placed in a separate subfolder. Select one of them. I select mop1.
![4](https://user-images.githubusercontent.com/34283881/116426277-37b30680-a858-11eb-83d3-4df21b77ee29.jpg)

4. After running the simulation, the results is generated in the folder. All the result files are "*.txt". 
![5](https://user-images.githubusercontent.com/34283881/116426937-cde72c80-a858-11eb-97b1-f6cc20f9d2ce.jpg)

5. We copy the content of each file to a Excel sheet and process them. Note that, three simulated MOPs generate the RPL control messages such as DIS, DIO and DAO. To generate data traffic, MOP2 needs to update to handle the source routing in the simulation.

Finally, feel free to ask any questions if there is a problem.
